### ISSUE TITLE
CM13 patching prints error, but patch works.

### ISSUE THREAD

**Issue by okias** [moosd/Needle#18]
I: Building apk file...
Exception in thread "main" brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_6695765770529305153.tmp, p, -F, /tmp/user/1000/tmpwbev4mrg/framework.jar.out/dist/framework.jar, -0, arsc, /tmp/user/1000/tmpwbev4mrg/framework.jar.out/build/apk]
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:425)
    at brut.androlib.Androlib.buildApk(Androlib.java:667)
    at brut.androlib.Androlib.build(Androlib.java:296)
    at brut.androlib.Androlib.build(Androlib.java:261)
    at brut.apktool.Main.cmdBuild(Main.java:225)
    at brut.apktool.Main.main(Main.java:84)
Caused by: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_6695765770529305153.tmp, p, -F, /tmp/user/1000/tmpwbev4mrg/framework.jar.out/dist/framework.jar, -0, arsc, /tmp/user/1000/tmpwbev4mrg/framework.jar.out/build/apk]
    at brut.util.OS.exec(OS.java:93)
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
    ... 5 more
Caused by: java.io.IOException: Cannot run program "/tmp/brut_util_Jar_6695765770529305153.tmp": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at java.lang.Runtime.exec(Runtime.java:620)
    at java.lang.Runtime.exec(Runtime.java:485)
    at brut.util.OS.exec(OS.java:84)
    ... 6 more
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    ... 9 more
 **\* Putting things back like nothing ever happened...

**Comment by souramoo** [comment]
This is an error with apktool trying to assemble the resources when the script is only really interested in the dex file. Now that smali/baksmali support multidex I will switch to using those in a future commit.

**Comment by ghost** [comment]
Another exception in CM 13

```
I: Smaling smali folder into classes.dex...
Exception in thread "main" org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65536
    at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
    at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:315)
    at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1025)
    at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:801)
    at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:250)
    at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:228)
    at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:57)
    at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:41)
    at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:378)
    at brut.androlib.Androlib.buildSources(Androlib.java:305)
    at brut.androlib.Androlib.build(Androlib.java:288)
    at brut.androlib.Androlib.build(Androlib.java:261)
    at brut.apktool.Main.cmdBuild(Main.java:225)
    at brut.apktool.Main.main(Main.java:84)

 *** Putting things back like nothing ever happened...
```

**Comment by ale5000-git** [comment]
@kehugter: You problem isn't related to the first one.
I have added a workaround some times ago for the problems like yours in [Tingle](https://github.com/ale5000-git/tingle).
If you try it, please report if it is working correctly.

**Comment by ghost** [comment]
@ale5000-git I got in a bootloop after restarting and I'm currently doing a fresh install. Thanks for the info and the link tho, will keep it in mind.

> If you try it, please report if it is working correctly.

I'm going for a ROM with spoofed signatures as embedded feature this time, I wont be able to test. I'll let you know in case I use your repo in the future.

**Comment by ale5000-git** [comment]
@kehugter: This is not related but resolving bootloop is easy, just keep a backup of original framework.jar, start the phone in recovery, connect the phone with usb cable to the pc and then push the original framework.jar through adb push.

**Comment by okias** [comment]
Fixed!

Good work, thank you.
