### ISSUE TITLE
Problem "framework.jar"

### ISSUE THREAD

**Issue by battosai50** [moosd/Needle#31]
Hello,

I can't make it work...I probably miss something obvious but can you help me?
Here's the log

H:\Softs\Huawei Ascend P7\Needle-master\Needle-master>patch.py
 **\* Selected device 7N2NEF1452015842
 **\* Device detected! proceeding...
 **\* Working dir: C:\Users\batto\AppData\Local\Temp\tmp7lp9q7xy
 **\* Rooting adbd...
adbd is already running as root
remount succeeded
 **\* Pulling framework from device...
2867 KB/s (38175 bytes in 0.013s)
 **\* Disassembling framework...
Exception in thread "main" org.jf.util.ExceptionWithContext: framework.jar is not an apk, dex file or odex file.
        at org.jf.dexlib2.DexFileFactory.loadDexFiles(DexFileFactory.java:140)
        at org.jf.dexlib2.DexFileFactory.loadDexFiles(DexFileFactory.java:81)
        at org.jf.baksmali.main.main(main.java:259)

Traceback (most recent call last):
  File "H:\Softs\Huawei Ascend P7\Needle-master\Needle-master\patch.py", line 67, in <module>
    subprocess.check_call(["java", "-jar", os.path.join(SCRIPT_DIR, "tools", "baksmali.jar"), "framework.jar", "-o", "classes", "-ls"])
  File "C:\Users\batto\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['java', '-jar', 'H:\Softs\Huawei Ascend P7\Needle-master\Needle-master\tools\baksmali.jar', 'framework.jar', '-o', 'classes', '-ls']' 
returned non-zero exit status 1

Probleme with extension ".jar"?
Will provide necessary informations about config if needed.
Thanks in advance

**Comment by ale5000-git** [comment]
I think the error is just misleading, if you framework.jar is small like 37KB it means that the code isn't here so your ROM is probably odexed.
If you don't deodex the ROM it will not work.

**Comment by anarcobuda** [comment]
I am facing the same issue at the moment. I have deodex'd my ROM and it still gives me this warning.
